language: rust
sudo: false
cache:
- apt
- cargo
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
notifications:
  slack:
    secure: jizX51L8CWq2WDLSQt/hPe0qPvy+KsocAIcBa8pBnmpFatNLxTliSxGRvLfQUPcekA+ja0DuY8OyeGyROkb5eFpyZ0DLbHYky4MRvzmJneFXbkNRzXPyDTsmu53/HCVx49nrKFgtKZXvUGdU5NqqXdG6PxZPSMyKPnT7uKrM4/m+PF/HkU7+96gEJ0TM7sN88hAk4P0zef0JvOzJvUO0Cr4bEJIa7+L4w1i9qaqpWeWRA8B7EDh2iQum4H571jpmZeBiEO3gxyRcj/tBORXDaXJZeTeZMEpvcZlOXqtmpD55KVyFyK/K2vFQboW1E7KTdyOi8CF2HbXllrBelg0fhU3jZFT5M0t/XMR4vMbLFrgk1XrlOP3Xx2vC0XevrfpugLjLDPYzov0A4bq3D2y/CfYURiAmx7YmwBr7/BWKk5aNHkH5nkq8Yo0INQJbxlIj2gFS86YeJaCUGEZ0x16eBCBktWKBKLfmGrQSuHkdXJtdk6qCeq/Iy0XkdJycYF+UJ0M0MsKzqItyQVqD5CalVNjb25PG72f8ihAi2EOvsxJ9qc3epBH+qZrrtCQYvggkVsNxQqyK6mX8hmMs4s2G3mKvrcQ5HIDDXebMiiJy6wTXjCvaPtsk0pxc7osrd1KrMFNvVAZLXhadzKKtyC5AGGDSgzCp0BN502V2guxqaLE=
