# -*- mode:toml; coding:utf-8-unix; -*-
# =============================================================================
[package]
name            = "column79"
version         = "0.1.0"
authors         = ["hanepjiv <hanepjiv@gmail.com>"]
license         = "MIT/Apache-2.0"
keywords        = ["utility"]
description     = ""
readme          = "README.md"
documentation   = "https://github.com/hanepjiv/column79-rs/wiki"
homepage        = "https://github.com/hanepjiv/column79-rs"
repository      = "https://github.com/hanepjiv/column79-rs.git"
# =============================================================================
[dependencies]
bitflags        = { default-features = false, version = "^0.8.0" }
env_logger      = { default-features = false, version = "^0.4.0" }
getopts         = { default-features = false, version = "^0.2.14" }
log             = { default-features = false, version = "^0.3.6" }
regex           = { default-features = false, version = "^0.2.1" }
tempfile        = { default-features = false, version = "^2.1.5" }
toml            = { default-features = false, version = "^0.2.1" }
# =============================================================================
[[bin]]
name            = "column79"
test            = true
doctest         = true
bench           = false
doc             = false
plugin          = false
harness         = true
