# -*- mode:toml; coding:utf-8-unix; -*-
# =============================================================================
[package]
name                    = "column79"
version                 = "0.2.2"
authors                 = ["hanepjiv <hanepjiv@gmail.com>"]
license                 = "MIT/Apache-2.0"
keywords                = ["tool", "development"]
description             = "Source code column checker."
readme                  = "README.md"
documentation           = "https://github.com/hanepjiv/column79-rs/wiki"
homepage                = "https://github.com/hanepjiv/column79-rs"
repository              = "https://github.com/hanepjiv/column79-rs.git"
publish                 = false
# =============================================================================
[dependencies]
bitflags                = { default-features = false, version = "^1.0.1" }
env_logger              = { default-features = false, version = "^0.5.6" }
getopts                 = { default-features = false, version = "^0.2.17" }
log                     = { default-features = false, version = "^0.4.1" }
regex                   = { default-features = false, version = "^0.2.10" }
serde                   = { default-features = false, version = "^1.0.37" }
serde_derive            = { default-features = false, version = "^1.0.37" }
tempfile                = { default-features = false, version = "^3.0.0" }
toml                    = { default-features = false, version = "^0.4.6" }
# =============================================================================
[[bin]]
name                    = "column79"
test                    = true
doctest                 = true
bench                   = false
doc                     = false
plugin                  = false
harness                 = true
